# Generated by Django 3.0.5 on 2020-04-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.CharField(choices=[(None, 'Select Station'), ('Station 1', 'Station 1'), ('Station 2', 'Station 2'), ('Station 3', 'Station 3'), ('Station N', 'Station N')], default=None, max_length=100)),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('otherSymptoms', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[(None, 'Select Type'), ('CharField', 'CharField'), ('DecimalField', 'DecimalField')], default=None, max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stayWellCore.Question')),
            ],
        ),
    ]
