# Generated by Django 3.0.5 on 2020-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[(None, 'Select Type'), ('CharField', 'CharField'), ('DecimalField', 'DecimalField')], default='CharField', max_length=200),
        ),
    ]
