# Generated by Django 3.0.5 on 2020-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0002_auto_20200408_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(choices=[(None, 'Select Type'), ('CharField', 'CharField'), ('DecimalField', 'DecimalField')], default='CharField', max_length=200),
        ),
    ]
