# Generated by Django 3.0.5 on 2020-04-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0003_auto_20200410_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fNumber',
            field=models.CharField(max_length=30),
        ),
    ]
