# Generated by Django 3.0.5 on 2020-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0003_auto_20200408_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_type',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[(None, 'Select Type'), ('CharField', 'CharField'), ('DecimalField', 'DecimalField')], default='CharField', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
