# Generated by Django 3.0.5 on 2020-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0004_auto_20200408_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='possible_choices',
            field=models.TextField(default='[insert]', max_length=200),
            preserve_default=False,
        ),
    ]
