# Generated by Django 3.0.5 on 2020-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayWellCore', '0004_auto_20200410_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBoolField',
        ),
        migrations.DeleteModel(
            name='QuestionCharField',
        ),
        migrations.DeleteModel(
            name='QuestionCharTest',
        ),
        migrations.DeleteModel(
            name='QuestionDecField',
        ),
        migrations.DeleteModel(
            name='QuestionDropDownField',
        ),
    ]
